function init(self)
	-- Add initialization code here
	-- Remove this function if not needed
	msg.post(".", "acquire_input_focus")
	self.message = "" -- <2>
end

function final(self)
end

function update(self, dt)
	-- Add update code here
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- print("On input: action_id=", action_id, " action=", action)
	if action_id == hash("type") then
		self.message = self.message .. action.text -- <3>
		-- print("DEBUG: msg=", self.message)
		local node = gui.get_node("test_name_text")
		-- local id = gui.get_id(node)
		gui.set_text(node, self.message)
		-- label.set_text("#test_name_text", self.message) -- <4>
	elseif action_id == hash("backspace") and action.repeated then
		local l = string.len(self.message)
		self.message = string.sub(self.message, 0, l-1) -- <5>
		local node = gui.get_node("test_name_text")
		gui.set_text(node, self.message)
		-- label.set_text(".#test_name_text", self.message) -- <6>
	end
end

function on_reload(self)
	-- Add input-handling code here
	-- Remove this function if not needed
end
